/* msg\alrload.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 101,116,104,101,114,100,102,115,32,105,115,32,97,108,114,101
  S001 db 97,100,121,32,105,110,115,116,97,108,108,101,100,32,97,110
  S002 db 100,32,99,97,110,110,111,116,32,98,101,32,108,111,97,100
  S003 db 101,100,32,116,119,105,99,101,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
