/* msg\noredir.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 82,101,100,105,114,101,99,116,111,114,32,105,110,115,116,97
  S001 db 108,108,97,116,105,111,110,32,104,97,115,32,98,101,101,110
  S002 db 32,102,111,114,98,105,100,100,101,110,32,101,105,116,104,101
  S003 db 114,32,98,121,32,68,79,83,32,111,114,32,97,110,111,116
  S004 db 104,101,114,32,112,114,111,99,101,115,115,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
