/* msg\notload.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 69,116,104,101,114,68,70,83,32,105,115,32,110,111,116,32
  S001 db 108,111,97,100,101,100,44,32,115,111,32,105,116,32,99,97
  S002 db 110,110,111,116,32,98,101,32,117,110,108,111,97,100,101,100
  S003 db 46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
