/* msg\pktdfail.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 80,97,99,107,101,116,32,100,114,105,118,101,114,32,105,110
  S001 db 105,116,105,97,108,105,122,97,116,105,111,110,32,102,97,105
  S002 db 108,101,100,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
