/* msg\tsrcomfa.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 67,111,109,109,117,110,105,99,97,116,105,111,110,32,119,105
  S001 db 116,104,32,116,104,101,32,84,83,82,32,102,97,105,108,101
  S002 db 100,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
